### ISSUE TITLE
Peer Review by 'Data Vizionaries'

### ISSUE THREAD

**Issue by srikrish2812** [INFO-526-FA24/project-2-insight-spark#1]
1. The team reviewing is datavizionaries. The details about the team members:
Maksim Kulik - h-akston
Himanshu Lal - hlarya-uoa
Kapil Parab - kapilparab
Abhay Kumara Sri Krishna Nandiraju - srikrish2812

2. Describe the goal of the project.
The goal is to analyze the trends in the unemployment rate in each state of the United States over time and identify the effects of events like the 2008 financial crisis and the COVID-19 pandemic on the unemployment rate. In addition to that, the project tends to identify the states that are vulnerable  and resilient during the unemployment years.

3. Describe the data used or collected.
This project analyzes the "Unemployment in America, Per US State" dataset from Kaggle. This dataset provides state-level unemployment statistics across the United States from 1976 to 2022, covering nearly five decades of labor market trends.
Key Dataset Features:
Time Frame: 1976–2022
Features: Total civilian labor force, employment, and unemployment rates by state and others
Potential insights: Allows analysis of regional disparities, economic recessions, and the impact of global crises on state economies
Source: Compiled from publicly available government labor reports with ongoing updates for current employment trends

4. Describe how the research question will be answered, e.g. what approaches / methods will be used.
The research question will be answered by analyzing trends and patterns in U.S. unemployment rates over time and across states. First, the Insight Spark team plans to use time series analysis to visualize the unemployment rate trends for each state with a line plot, marking key economic events to highlight their impact. Then summary statistics could be used to provide insights into state-by-state variability and help detect outliers, supporting a deeper understanding of temporal and spatial trends in unemployment. Finally, They also mention an animated choropleth map that could illustrate the geographical distribution of unemployment, allowing for an easy comparison of rates across states over time.

5. Is there anything that is unclear from the proposal?
The proposal is very well structured: the dataset is explained in great detail, the reasoning process for choosing this dataset is compelling, the analysis plan looks thorough and fits the research questions and the data well. The weekly plan also looks realistic and distributes the work evenly.

6. Provide constructive feedback on how the team might be able to improve their project.
The proposal is great overall, but our team wished we had more details regarding the research questions. This part of the proposal looks like it may be a bit too brief, especially when compared to all the other sections of the proposal.

7. What aspect of this project are you most interested in and would like to see highlighted in the presentation?
Our team is most interested in observing the heatmap depicting the states that are most resilient to the effects of the 2008 financial crisis on the unemployment rate. Moreover, we would like to look at the EDA performed on the dataset.

8. Provide constructive feedback on any issues with file and/or code organization.
When we tried to render the proposal.qmd, it stopped because the dataset was not uploaded to the repository. It would have been helpful if the dataset was uploaded to the github repository.

9. (Optional) Any further comments or feedback?

**Comment by nithingm** [comment]
Made the following changes:
We've now added more details to the research questions. 
The proposal.qmd file should be easily rendered now. Please feel free to check and get back to us in case of any issues.
Dataset has been added to the repository

**Comment by nithingm** [comment]
Closing Issue
