### ISSUE TITLE
instructor review 

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-insight-spark#3]
Hello team insight spark - 

Your project proposal appears to be set up for success. There is a data set that needs some wrangling and mutation.  Research questions are interesting and answerable by the approaches you outlined. Looking forward to your interpretations and findings. 

One area of consideration that I do not see is addressed int he proposal is the approach to the poster presentation. As a team, spend some time storyboarding the poster and consider how such an ambitious project will be translated into a poster.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |     3   |
| Proposal | 5         |    5    |
| Workflow | 1         |     1   |
| Teamwork | 1         |      1  |
| Total    | 10        |     10   |

**Comment by Disha-98** [comment]
Thank you for the feedback! We will dedicate time to storyboarding the poster to ensure clear and effective communication of our findings.
