### ISSUE TITLE
Team Pixels and Patterns

### ISSUE THREAD

**Issue by sindhugoshika** [INFO-526-FA24/project-2-insight-spark#4]
Hello Team Insight Spark,

Your overall poster is fantastic! The visualizations flow beautifully and are well-connected, almost like a storyline.

However, I’d love to see how the relationship between population and unemployment is portrayed. Incorporating this into your plot might be challenging, but I’m excited to see how you tackle it. Wishing you all the best!

Team Pixels and Patterns

**Comment by ronymacwan** [comment]
Thank you team Team Pixels and Patterns for providing this feedback.
Yes, we already have state-wise population and employment/unemployment rates in our dataset. We have done some analysis on finding trends in the most and least populous states. However, these insights are not part of the poster, but will be included in our write-up and class presentation.
