### ISSUE TITLE
Review of Poster by DataWaves Team

### ISSUE THREAD

**Issue by libin-n-g** [INFO-526-FA24/project-2-insight-spark#5]
### 1. What is the good thing in the poster?  
The presentation is visually appealing and effectively uses visualization to convey information. The data representation is clear, making it easy for the audience to understand the content.

### 2. What do you think can/should be improved?  
- **Labeling**: Increase the size of the labels to improve readability, especially for critical elements.  
- **Legend Color Scheme**: Reverse the color gradient on the legend for the US map. A lighter color should represent a lower level of unemployment, while a darker color should indicate higher unemployment levels for better alignment with intuitive data interpretation.

---

**This review was conducted by @INFO-526-FA24/datawaves .**

**Comment by ronymacwan** [comment]
Thank you team DataWaves for the thoughtful suggestions. Increasing the label size is a great idea, and we will make adjustments to enhance readability for critical elements. We also appreciate the feedback on the legend color scheme for the US map. We will reverse the color gradient to ensure that a lighter color represents lower unemployment and a darker color indicates higher unemployment.
