### ISSUE TITLE
Review of Poster by Data Vizionaries

### ISSUE THREAD

**Issue by kapilparab** [INFO-526-FA24/project-2-insight-spark#6]
1. What is the good thing in the poster?

The distribution map is really detailed and conveys the data clearly.

2. What do you think can/should be improved?

State level unemployment trends has two separate entries for New York. One for NYC and other for the state. Combining both could provide a clearer picture of New York.

**Comment by ronymacwan** [comment]
Thank you Team Data Vizionaries for the feedback. New York (state) and NYC (city) were two different entities in our dataset. We felt that including them as distinct entities in our analysis made more sense to highlight the distinction. However, your point is valid for state-level analysis. We will ensure that NYC records are included in New York state when we further carry out state-level analysis.
