### ISSUE TITLE
Review from Visual Voyagers

### ISSUE THREAD

**Issue by Tusharvimal** [INFO-526-FA24/project-2-insight-spark#7]
1. What is the good thing in the poster?
The poster is really good and the visualization shows how the unemployment and the employment are totally dependent on each other clearly.

2. What do you think can/should be improved?
Make the plots labels more clear and give conclusion which you got after observing all the patterns and the visualization.

**Comment by ronymacwan** [comment]
Thank you Team Visual Voyagers. Yes, we are still working on different trends related to employment and unemployment. Once we finalize the figures to present to the class, we will add suitable conclusions to complement them.
