### ISSUE TITLE
Review from team Data Nexus

### ISSUE THREAD

**Issue by SiddheshwarSinghNegi** [INFO-526-FA24/project-2-insight-spark#8]
Strengths: The poster stands out with its visually appealing design, utilizing well-crafted visualizations to effectively present information. The data is organized in a way that ensures clarity, making it easy for the audience to follow and interpret the key points. The thoughtful design enhances engagement and demonstrates a strong understanding of how to communicate data effectively.

Weaknesses: The labels on the poster could be larger to improve visibility, especially for essential data elements. This adjustment would make the content more readable and accessible to viewers. The color gradient on the US map's legend may benefit from being adjusted.

**Comment by ronymacwan** [comment]
Thank you team Data Nexus for the feedback. We will make the labels larger for better visibility and adjust the color gradient on the US map's legend to enhance readability and accessibility.
